 jq '.timestamp' log/views/15h/logs_view_1.json
 jq '.timestamp' log/views/15h/logs_view_2.json
 jq '.timestamp' log/views/15h/logs_view_3.json
 jq '.timestamp' log/views/15h/logs_view_4.json
 jq '.timestamp' log/views/15h/logs_view_5.json
 jq '.timestamp' log/views/15h/logs_view_6.json
 jq '.timestamp' log/views/15h/logs_view_7.json
 jq '.timestamp' log/views/15h/logs_view_8.json
 jq '.timestamp' log/views/15h/logs_view_9.json
 jq '.timestamp' log/views/15h/logs_view_10.json
 jq '.timestamp' log/views/15h/logs_view_11.json
 jq '.timestamp' log/views/15h/logs_view_12.json
 jq '.timestamp' log/views/15h/logs_view_13.json
 jq '.timestamp' log/views/15h/logs_view_14.json
 jq '.timestamp' log/views/15h/logs_view_15.json
 jq '.timestamp' log/views/15h/logs_view_16.json
 jq '.timestamp' log/views/15h/logs_view_17.json
 jq '.timestamp' log/views/15h/logs_view_18.json
 jq '.timestamp' log/views/15h/logs_view_19.json
 jq '.timestamp' log/views/15h/logs_view_20.json
jq '.timestamp' log/views/15h/logs_view_21.json
jq '.timestamp' log/views/15h/logs_view_22.json
jq '.timestamp' log/views/15h/logs_view_23.json
jq '.timestamp' log/views/15h/logs_view_24.json
jq '.timestamp' log/views/15h/logs_view_25.json
jq '.timestamp' log/views/15h/logs_view_26.json
jq '.timestamp' log/views/15h/logs_view_27.json
jq '.timestamp' log/views/15h/logs_view_28.json
jq '.timestamp' log/views/15h/logs_view_29.json
jq '.timestamp' log/views/15h/logs_view_30.json
jq '.timestamp' log/views/15h/logs_view_31.json
jq '.timestamp' log/views/15h/logs_view_32.json
jq '.timestamp' log/views/15h/logs_view_33.json
jq '.timestamp' log/views/15h/logs_view_34.json
jq '.timestamp' log/views/15h/logs_view_35.json
jq '.timestamp' log/views/15h/logs_view_36.json
jq '.timestamp' log/views/15h/logs_view_37.json
jq '.timestamp' log/views/15h/logs_view_38.json
jq '.timestamp' log/views/15h/logs_view_39.json
jq '.timestamp' log/views/15h/logs_view_40.json
jq '.timestamp' log/views/15h/logs_view_41.json
jq '.timestamp' log/views/15h/logs_view_42.json
jq '.timestamp' log/views/15h/logs_view_43.json
jq '.timestamp' log/views/15h/logs_view_44.json
jq '.timestamp' log/views/15h/logs_view_45.json
jq '.timestamp' log/views/15h/logs_view_46.json
jq '.timestamp' log/views/15h/logs_view_47.json
jq '.timestamp' log/views/15h/logs_view_48.json
jq '.timestamp' log/views/15h/logs_view_49.json
jq '.timestamp' log/views/15h/logs_view_50.json
jq '.timestamp' log/views/15h/logs_view_51.json
jq '.timestamp' log/views/15h/logs_view_52.json
jq '.timestamp' log/views/15h/logs_view_53.json
jq '.timestamp' log/views/15h/logs_view_54.json